### ISSUE TITLE
Unable resolve srv record

### ISSUE THREAD

**Issue by ufm** [YGGverse/web-api#1]
```
host -t srv _matrix._tcp.twinkle.ygg
_matrix._tcp.twinkle.ygg has SRV record 1 1 8448 ygg.twinkle.lol.
```

But on query `http://[201:23b4:991a:634d:8359:4521:5576:15b7]/dns/dig.php?name=_matrix._tcp.twinkle.ygg&records[]=SRV&records[]=AAAA` I got
```
success	false
message	"valid name required"
```

**Comment by d47081** [comment]
`valid name required` means that domain name does not match [filter condition](https://github.com/YGGverse/net-php/blob/main/src/Dig.php#L21)

according to documentation:
https://www.php.net/manual/en/filter.filters.validate.php
> Validates domain names against RFC 1034, RFC 1035, RFC 952, RFC 1123, RFC 2732, RFC 2181, and RFC 1123. Optional flag FILTER_FLAG_HOSTNAME adds ability to specifically validate hostnames (they must start with an alphanumeric character and contain only alphanumerics or hyphens).

p.s. SRV record is [not implemented](https://github.com/YGGverse/net-php/blob/main/src/Dig.php#L9) yet as every type defined in library requires strict std out validation also

p.p.s. project name was updated, now related link on example is
`http://[201:23b4:991a:634d:8359:4521:5576:15b7]/api/net/dig.php?name=_matrix._tcp.twinkle.ygg&records[]=SRV&records[]=AAAA`

**Comment by d47081** [comment]
SRV now supported, including solution for `_`
https://github.com/YGGverse/net-php/commit/60114e9d1e19731b79b7a0de7824164d7a288d7e
